### ISSUE TITLE
ttl health check result is posted before service is registered

### ISSUE THREAD

**Issue by wleese** [joyent/containerbuddy#101]
The first thing my container does is:

PUT /v1/agent/check/pass/tst-logredis2-tst-5a49064b027c?note=ok&token=xxxxxxxxxxxxx

Which fails with (output from tcpdump):

HTTP/1.1 500 Internal Server Error
Date: Fri, 04 Mar 2016 08:29:42 GMT
Content-Length: 36
Content-Type: text/plain; charset=utf-8

CheckID does not have associated TTL

Consul agent logs:
Mar  4 09:59:27 tst-xxxx\-xxxx-001 consul: 2016/03/04 09:59:27 [ERR] http: Request PUT /v1/agent/check/pass/tst-logredis2-tst-5a49064b027c?note=ok&token=<hidden>, error: CheckID does not have associated TTL from=X.X.X.X:60299

Afterwards containerbuddy registers the service and check (just the check tcpdump below)

PUT /v1/agent/check/register?token=x
{"ID":"tst-logredis2-tst-5a49064b027c","Name":"tst-logredis2-tst-5a49064b027c","Notes":"TTL for tst-logredis2-tst set by containerbuddy","ServiceID":"tst-logredis2-tst-5a49064b027c","TTL":"30s"}
This behaviour seems incorrect - shouldn't the service be registered first?

Here's my app.json:
```

{
  "consul": "{{.HOST}}:8500",
  "stopTimeout": -1,
  "services": [
    {
      "name": "tst-logredis2-tst",
      "port": 8080,
      "health": [
        "socat",
        "-",
        "TCP4:localhost:8080"
      ],
      "poll": 10,
      "ttl": 30,
      "interfaces": [
        "eth0[0]",
        "x.x.x.x/16",
        "inet",
        "inet6"
      ]
    }
  ]
}

```

**Comment by tgross** [comment]
This is intentional. We send a heartbeat and if we get a message back from the discovery service that our service isn't registered, we then register it. We need to do this anyway in order to handle the error condition, so we lazily register to avoid having to check-and-set (making 2 requests for each heartbeat), and it reduces the amount of time it takes for an instance to be marked live by the discovery service on start.

See [this section of the code](https://github.com/joyent/containerbuddy/blob/68c06d03770c0a1684dca6eaea9b5c3848949796/containerbuddy/consul.go#L43-L56) for the implementation. Note that strictly speaking this is an implementation detail of the Consul and Etcd backends, not a specification we're defining. Some future backend could implement this differently depending on that backend's semantics.

**Comment by wleese** [comment]
Ah, skimmed right over that. Closing then.
