### ISSUE TITLE
Signal could not be handled

### ISSUE THREAD

**Issue by yingfeng** [joyent/containerbuddy#98]
According to the description, containerbuddy accepts POSIX signals to change its runtime behavior. However, when we test it, we've found that the signals could not be accepted by the process at all, and after we dive into the code, we've got some hints:

```
        //Line 25 in containerbuddy/main.go 
	// Run the onStart handler, if any, and exit if it returns an error
	if onStartCode, err := run(config.onStartCmd); err != nil {
		os.Exit(onStartCode)
	}

	// Set up handlers for polling and to accept signal interrupts
	if 1 == os.Getpid() {
		reapChildren()
	}
	handleSignals(config)
	handlePolling(config)
```

In the above code snippet, handleSignals would not be called untill the "run" procedure has been executed, however, "run" procedure would be blocked untill the process itself quit.   Given such design, handleSignals would not take into effects at all. 

So is this a bug for such design?  A similar project is https://github.com/Yelp/dumb-init , its signal handler could work correctly.

**Comment by tgross** [comment]
> In the above code snippet, handleSignals would not be called untill the "run" procedure has been executed, however, "run" procedure would be blocked untill the process itself quit. Given such design, handleSignals would not take into effects at all. So is this a bug for such design?

No, this is the intended behavior.

The `onStart` must run to completion before any of the signal handlers start up. This deliberately prevents signals from being handled before the main application is running (found in the next block of code). Instead, signals will be unhandled and you'll get the default Posix signals behavior (typically terminating the container process). Otherwise we would get the following incorrect behaviors:

- the SIGTERM handler could try to terminate a child process that doesn't exist
- the SIGHUP handler could fire before the configuration file is finalized by an `onStart` handler (ex. [triton-mysql](https://github.com/tgross/triton-mysql/blob/master/bin/triton-mysql.py))
- the SIGUSR1 handler could fire and try to deregister a service that hasn't yet been registered

If you have problems receiving signals because of an `onStart` handler then you may be misconfiguring Containerbuddy. The application that you're trying to shim with Containerbuddy should be passed as the arguments to Containerbuddy binary (like in [this Dockerfile](https://github.com/joyent/containerbuddy/blob/a08ff35b10a6a149cd3d6715a3359d4cb84d0c6b/integration_tests/fixtures/nginx/Dockerfile#L29-L30)), not as arguments to the `onStart` handler.

I'll be happy to help you debug the configuration if you share it in this issue.

**Comment by yingfeng** [comment]
Thank you. I made a mistake that the above code snippet is to run "onStart" handler instead of the Containerbuddy binary itself, in that case, the signal behavior is correct as expected.
