### ISSUE TITLE
Update links for examples

### ISSUE THREAD

**Issue by xynova** [joyent/containerbuddy#99]
Just a few days ago there was a folder with example files and now it has gone missing. A few links comming from the blog are broken now.

**Comment by tgross** [comment]
@xynova we moved the examples into the integration tests  in this PR https://github.com/joyent/containerbuddy/pull/94 because they were in danger of getting stale every time we added a new feature.

Thanks for the tip on the blog links... I'll go through and make sure those get updated. We'll also be posting a much more extensive example, including step-by-step instructions for applying the pattern to your own applications, later today on joyent.com/blog

**Comment by tgross** [comment]
In the meantime, @xynova you can get those examples at https://github.com/joyent/containerbuddy/tree/1.0.0/examples

**Comment by tgross** [comment]
@xynova this was published just now at http://www.joyent.com/blog/applications-on-autopilot.
